OD-16881 Fix console.error/warnings generated in client jest tests (#760)
* OD-16881 Jest test fixed error/warnings: MUI: Unable to find the input element. It was resolved to [object HTMLTextAreaElement] while an HTMLInputElement was expected. Instead, Autocomplete expects an input element.

* OD-16881 Jest test fixed error/warnings: updated articleProduct component test and mock data and added plain system user mock data for dashboard.

* OD-16881 Jest test fixed error/warnings: Removed css warnings, fixed import material createStyles, fixed dashboard chart width, added plain mock data for audits.

* OD-16881 Jest test fixed error/warnings: Fixed nested <p> tag issue, fixed autocomplete input field, fixed state updating issue for nested list view form field, and fixed canvas issue for jest test.

* OD-16881 Jest test fixed error/warnings: Fixed error Failed prop type: Invalid prop `disabled` of type `number` supplied to `ForwardRef(Input)`, expected `boolean`.

* OD-16881 Jest test fixed error/warnings: Warning: Received NaN for the `size` attribute. If this is expected, cast the value to a string.

* OD-16881 Jest test fixed error/warnings: Fixed warning: Received NaN for the `size` attribute. If this is expected, cast the value to a string.

* OD-16881 Jest test fixed error/warnings: Fixed course class duplicate modals.

* OD-16881 Jest test fixed error/warnings: Fixed Warning: Failed prop type: The prop `onSubmit` is marked as required in `Form`, but its value is `undefined`.

* OD-16881 Jest test fixed error/warnings: Fixed state props for initial values, fixed position of trigger event and validate each field for expect, reduce mock data of custom fields, and removed afer each cleanup for jest test

* OD-16881 Jest test fixed error/warnings: Increased jest test timeout.

* OD-16881 Jest test fixed error/warnings: Fixed Warning: Failed prop type: The prop `xs` of `Grid` can only be used together with the `item` prop.

* OD-16881 Jest test fixed error/warnings: Fixed line 1:0 mismatched input '<EOF>' expecting {'(', '#', '@', LIKE, NOT, Identifier} and MUI: The key `icon` provided to the classes prop is not implemented in DocumentsRenderer. You can only override one of the following: dropInfo,addButton,documentGridItem.

* OD-16881 Jest test fixed error/warnings: Fixed Warning: Received NaN for the `size` attribute. If this is expected, cast the value to a string.

* OD-16881 Jest test fixed error/warnings: Fixed error TS1128: Declaration or statement expected and fixed Warning: Each child in a list should have a unique "key" prop.

Co-authored-by: Yury Yasuchenya <yury@ish.com.au>